using Microsoft.EntityFrameworkCore.Query.Associations.ComplexTableSplitting;

using Xunit.Abstractions;

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query.Associations.ComplexTableSplitting;

public class ComplexTableSplittingMiscellaneousCalciteTest(ComplexTableSplittingCalciteFixture fixture, ITestOutputHelper testOutputHelper) :
    ComplexTableSplittingMiscellaneousRelationalTestBase<ComplexTableSplittingCalciteFixture>(fixture, testOutputHelper);

